name: Tests

on:
  push:
    branches:
      - main
    paths:
      - simple_strings/**
      - tests/**
  pull_request:
    types: [opened, synchronize]
    paths:
      - simple_strings/**
      - tests/**
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: "Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)"
        required: false
        default: false


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Set up GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: latest
          platform: x64
      - name: Set up gcovr
        run: |
          python -m pip install --upgrade pip
          python -m pip install gcovr
      - name: Set up googletest
        run: |
          sudo apt-get -y install git cmake
          git clone https://github.com/google/googletest.git -b release-1.11.0
          cd googletest
          mkdir build
          cd build
          cmake -DBUILD_GMOCK=OFF ..
          make
          sudo make install
          cd ../..
          rm -Rf googletest
      - uses: actions/checkout@v3
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled }}
        with:
          limit-access-to-actor: true
      - name: Tests
        run: |
          make tests
          ./tests/tests
      - name: Generate coverage
        run: |
          gcovr --cobertura coverage.xml
      - name: Upload coverage
        uses: codecov/codecov-action@v2
        with:
          files: coverage.xml
          fail_ci_if_error: true
